name: Deploy to EC2

on:
  push:
    branches:
      - master  # Trigger on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out the repository code

      # Step 2: Set up SSH for connecting to EC2 instance
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the SSH private key stored in GitHub Secrets

      # Step 3: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@44.203.93.213 << 'EOF'
            # Navigate to the project directory on EC2
            cd /home/ubuntu/EC2  # Ensure this path exists on your EC2

            # Pull the latest code from the GitHub repository directly
            #git pull origin master

            # Install dependencies using npm (this will run on the EC2 instance)
            

            # Restart the app using PM2
             pm2 restart index.js  # Replace with your entry file if necessary
           
          EOF
